### ISSUE TITLE
Equipes - Majeure - Impossibilité de création d’alliance

### ISSUE THREAD

**Issue by Maeglin1908** [guortatesOfficial/The-Very-Little-War#1]
**Sujets**
- https://www.theverylittlewar.com/sujet.php?id=973
- https://www.theverylittlewar.com/sujet.php?id=1059
- https://www.theverylittlewar.com/sujet.php?id=1084  

**Description**

Il est parfois impossible de créer une alliance, dans des conditions à déterminer.  

**Suggestion**

None

**Comment by Maeglin1908** [comment]
Le bout de code suivant est responsable du message d'erreur : 
`if (preg_match("#^[a-zA-Z0-9_]{3,16}$#", $_POST['tagalliance'])) {`

Solution en local : Changement du message d'erreur pour être plus précis.
`"Le TAG de l'alliance ne peut être composé que de lettres, nombres, "_", entre 3 et 16 caractères."`

**Comment by dulphMain** [comment]
Il faut aussi ajouter la condition sur allianceadmin.php au moment de changer le nom de l'alliance. Il n'y a pas de condition pour ça, c'est ce qui permet la création de mon alliance. (2ème D. B.)
