### ISSUE TITLE
Corrections de textes

### ISSUE THREAD

**Issue by Maeglin1908** [guortatesOfficial/The-Very-Little-War#40]
### Historique des versions

Emplacement: Historique des versions, juste en dessous de 2.0.0.0  
Texte actuel: Version 1.5.0.0  
Texte corrigé: Version 1.7.0.0

### Messages envoyés 

Emplacement: Messages envoyés  
Texte actuel: Auteur  
Texte corrigé: Destinataire

### Sujets verrouillés

Emplacement: Sujets verrouillés  
Texte actuel: vérouillé  
Texte corrigé: verrouillé

### Listes des sujets (légende)

Emplacement: Listes des sujets (légende)  
Texte actuel: Sujet vérouillé  
Texte corrigé: Sujet verrouillé

**Comment by dulphMain** [comment]
La version 1.5.0.0 en double n'est pas une version 1.7.0.0 mal notée, il s'agit d'une duplication de la version 1.5.0.0. On a pas les vrais changelogs de la version 1.7.0.0. Comparer avec l'autre version 1.5.0.0
